//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.Product_materials = new HashSet<Product_materials>();
        }
    
        public int ID_Material { get; set; }
        public string NameMaterial { get; set; }
        public Nullable<int> IDTypeMaterial { get; set; }
        public Nullable<double> PriceEdMaterial { get; set; }
        public Nullable<int> QuantitySklad { get; set; }
        public Nullable<int> MinQuantity { get; set; }
        public Nullable<int> QuantityUpakovka { get; set; }
        public Nullable<int> IDEdIzmerenie { get; set; }
    
        public virtual Izmerenie Izmerenie { get; set; }
        public virtual Material_type Material_type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product_materials> Product_materials { get; set; }
    }
}
