//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test.Classes
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_materials
    {
        public int ID_ProductMaterial { get; set; }
        public Nullable<int> IDProduct { get; set; }
        public Nullable<int> IDMaterial { get; set; }
        public Nullable<double> NuzhnoQuantityMaterial { get; set; }
    
        public virtual Materials Materials { get; set; }
        public virtual Products Products { get; set; }
    }
}
